services:
  receipts-db:
    image: mongo:latest
    container_name: receipts-db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - receipts-db:/data/db
    command:
      - "--auth"
  receipts-api:
    image: ghcr.io/veselin.antonov/receipts-api/receipts-api:latest
    container_name: receipts-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - receipts-db
    env_file: "./.env"

volumes:
  receipts-db:
    name: receipts-db