spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}

      authentication-database: ${MONGODB_AUTH_DB}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASS}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: ${PORT}